# Generated by Django 5.2.6 on 2025-10-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dinheirocaixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadespesas',
            options={'verbose_name': 'Categoria de Despesa', 'verbose_name_plural': 'Categorias de Despesas'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data',
        ),
    ]
