# Generated by Django 5.2.6 on 2025-10-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoriadespesas_options_remove_despesa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
