# Generated by Django 5.2.6 on 2025-10-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_despesa_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiromes',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Fechamento Financeiro Mensal', 'verbose_name_plural': 'Fechamentos Financeiros Mensais'},
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='lucro_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='lucro_potencial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='total_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='total_ganho_potencial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financeiromes',
            name='total_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financeiromes',
            name='ano',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='financeiromes',
            name='mes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
