# Generated by Django 5.2.6 on 2025-10-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_financeiromes_options_financeiromes_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
