# Generated by Django 5.2.6 on 2025-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venda_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
