# Generated by Django 5.2.6 on 2025-11-25 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produtos_preco_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AberturaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberturas_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa do Dia',
                'verbose_name_plural': 'Caixas do Dia',
            },
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=2)),
                ('data_fechamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('abertura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamento', to='core.aberturacaixa')),
            ],
            options={
                'verbose_name': 'Fechamento do Caixa',
                'verbose_name_plural': 'Fechamento do Caixa',
            },
        ),
        migrations.CreateModel(
            name='SaidaCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('valor_saida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saída do Caixa',
                'verbose_name_plural': 'Saídas do Caixa',
            },
        ),
        migrations.DeleteModel(
            name='DinheiroCaixa',
        ),
    ]
