# Generated by Django 5.2.6 on 2025-11-25 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_venda_usuario_aberturacaixa_fechamentocaixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturacaixa',
            name='fechado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saidacaixa',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
