# Generated by Django 5.2.6 on 2025-11-25 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aberturacaixa_fechado_saidacaixa_data_saida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentocaixa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_caixa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
