# Generated by Django 5.2.6 on 2025-11-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fechamentocaixa_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aberturacaixa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aberturacaixa',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='aberturacaixa',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='criacao',
        ),
    ]
