# Generated by Django 5.2.6 on 2025-11-25 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_aberturacaixa_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='abertura',
        ),
        migrations.AlterModelOptions(
            name='fechamentocaixa',
            options={'verbose_name': 'Fechamento de Caixa', 'verbose_name_plural': 'Fechamentos de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='saidacaixa',
            options={'verbose_name': 'Movimentação de Saída', 'verbose_name_plural': 'Movimentações de Saída'},
        ),
        migrations.RenameField(
            model_name='saidacaixa',
            old_name='valor_anterior',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='valor_atual',
        ),
        migrations.RemoveField(
            model_name='saidacaixa',
            name='valor_saida',
        ),
        migrations.AddField(
            model_name='saidacaixa',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saidacaixa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechado', models.BooleanField(default=False)),
                ('usuario_abertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
            },
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='caixa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechamento', to='core.caixa'),
        ),
        migrations.AddField(
            model_name='saidacaixa',
            name='caixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='core.caixa'),
        ),
        migrations.DeleteModel(
            name='AberturaCaixa',
        ),
    ]
