# Generated by Django 5.2.6 on 2025-11-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_fechamentocaixa_abertura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='fechado',
            new_name='status',
        ),
    ]
