# Generated by Django 5.2.6 on 2025-11-26 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_fechado_caixa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fechamentocaixa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saidacaixa',
            options={},
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(fields=('usuario_abertura', 'data_abertura'), name='caixa_unico_por_usuario_dia'),
        ),
    ]
